# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  username: genaoexkacqyqt
  password: g-qwtynoK5K6edPGDDrlM7YsMA
  
development:
  <<: *default
  database: df63o8hjr0s3tt
 
  
test:
  <<: *default
  database: df63o8hjr0s3tt
  

production:
  <<: *default
  database: df63o8hjr0s3tt
  
